name = "duganlabs"
main = "index.js"
compatibility_date = "2026-04-04"
compatibility_flags = ["nodejs_compat"]

routes = [
  { pattern = "duganlabs.com/*", zone_name = "duganlabs.com" },
  { pattern = "www.duganlabs.com/*", zone_name = "duganlabs.com" }
]

[[kv_namespaces]]
binding = "BLOG"
id = "6abd29c8014f4b70add446dc20cd9c06"

[[kv_namespaces]]
binding = "REGISTRY"
id = "f47c0f5887f54a45ab4ef1f2f75a6b62"

[assets]
directory = "../pages"
binding = "ASSETS"
run_worker_first = true
